name: rivet
description: A high-performance, type-safe, full-stack web framework for Dart with built-in JWT, WebSockets, and Admin Panel.
version: 1.0.0
repository: https://github.com/rivet-framework/rivet

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  dart_jsonwebtoken: ^3.3.1
  mime: ^2.0.0
  mongo_dart: ^0.10.5
  mysql1: ^0.20.0
  path: ^1.9.1
  postgres: ^3.5.9
  watcher: ^1.1.4
  args: ^2.4.0
  analyzer: ^6.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
